Interfaces=function(){var g=function(a,b){this.type=a;if(this.options=b)this.options.include&&(this.options.include=[].concat(this.options.include)),this.options.exclude&&(this.options.exclude=[].concat(this.options.exclude))};g.prototype.requiredBy=function(a){var b;if(a&&this.options){if(this.options.include){for(b=0;b<this.options.include.length;++b)if(this.options.include[b]===a)return!0;return!1}if(this.options.exclude)for(b=0;b<this.options.exclude.length;++b)if(this.options.exclude[b]===a)return!1}return!0};
g.prototype.isSyncronized=function(){return this.options&&!0===this.options.sync};g.prototype.isSyncronousFunction=function(){return this.type===Interfaces.TYPE_SYNC_FUNCTION};g.prototype.isFunction=function(){return this.type===Interfaces.TYPE_FUNCTION||this.type===Interfaces.TYPE_SYNC_FUNCTION};g.prototype.isConstructor=function(){return this.type===Interfaces.TYPE_CONSTRUCTOR};g.prototype.isPrimitive=function(){return!this.isFunction()&&!this.isConstructor()};g.prototype.shouldSendIndirect=function(){return this.options&&
!0===this.options.sendIndirect};g.prototype.allowWrite=function(){return this.options&&!0===this.options.write};g.prototype.addIncludes=function(a){this.options=this.options||{};this.options.include=this.options.include.concat(a)};var b=function(a,b){return function(){return b.apply(a,arguments)}},d=function(a,b,c){if("function"===typeof c.requestFunction)return function(){for(var d=[],e=0,f=arguments.length;e<f;++e)d.push(arguments[e]);return LPMessaging.makeRequest(c.requestFunction,0<a.length?
a.concat(b):b,d)};throw"requestFunction must be specified for this interface since it is not direct access.";},h=function(a,b,c){return function(){"function"===typeof b&&b.apply(a,arguments);"function"===typeof c&&c.apply(a,arguments)}},e=function(a,c,f,p,n,k){var q=!1,l=[],j;for(j in p){var m=p[j];m instanceof g?m.isFunction()?m.requiredBy(k.context)&&(k.direct||m.isSyncronousFunction()?"object"===typeof c&&"function"===typeof c[j]?(a[j]=b(c,c[j]),!k.direct&&m.shouldSendIndirect()&&(a[j]=h(a,a[j],
d(n,j,k)))):l.push(m.type+": "+n.concat(j).join(".")):a[j]=d(n,j,k)):m.isConstructor()?m.requiredBy(k.context)&&("object"===typeof c&&"function"===typeof c[j]?a[j]=c[j]:l.push(m.type+": "+n.concat(j).join("."))):q=!0:(a.hasOwnProperty(j)||(a[j]={}),e(a[j],c?c[j]:c,f?f[j]:f,p[j],n.concat(j),k))}if(q){a.get=function(a){if(p.hasOwnProperty(a))return f[a];throw a+" is not defined in the interface.";};var r=function(a,b,c){if(!a.allowWrite())throw n.concat(b)+" is not writeable.";if(a&&typeof c===a.type)f[b]=
c;else throw b+" is not defined in the interface.";};a.set=k.direct?function(a,b){r(p[a],a,b)}:function(a,b){var c=p[a];r(c,a,b);c.shouldSendIndirect()&&LPMessaging.makeRequest(k.requestFunction,"LPData.setValue",[n.concat(a),b])}}if(0<l.length)throw"Background instance does not support the following:\n"+l.join("\n");return a},f={},c={},a=function(b,c,d,e){var f=[],k;for(k in b){var h=e?e.concat(k):[k],l=b[k];l instanceof g?l.isPrimitive()&&(l.requiredBy(c)&&(!d||l.isSyncronized()))&&f.push({sourceFunction:l.options&&
l.options.sourceFunction,path:h}):f=f.concat(a(l,c,d,h))}return f};return{TYPE_CONSTRUCTOR:"contsructor",TYPE_SYNC_FUNCTION:"synchronous function",TYPE_FUNCTION:"function",TYPE_STRING:"string",TYPE_BOOLEAN:"boolean",TYPE_NUMBER:"number",TYPE_OBJECT:"object",Definition:g,extend:function(a,b){for(var c in b){var d=b[c];switch(typeof d){case "object":a.hasOwnProperty(c)?Interfaces.extend(a[c],d):a[c]=d;break;default:a[c]=d}}},createInstance:function(a,b){return e(b.instance||{},b.source||b.sourceFunctions,
b.source||b.sourceData,a,[],b)},getPrimitives:function(b){var d={},e=b.context||"",g;b.syncronizedOnly?(g=c[e],"undefined"===typeof g&&(g=c[e]=a(b.interface,e,!0))):(g=f[e],"undefined"===typeof g&&(g=f[e]=a(b.interface,e,!1)));for(var e=0,h=g.length;e<h;++e){var k=g[e],q;q=k.sourceFunction?"function"===typeof k.sourceFunction?k.sourceFunction():LPReflection.callFunction(null,k.sourceFunction,[],{context:b.source}):LPReflection.getValue(b.interface,k.path,{context:b.source});LPReflection.setValue(null,
k.path,q,{context:d})}return d}}}();
Interfaces.BackgroundInterface=function(g){var b=g.TYPE_FUNCTION,d=g.TYPE_SYNC_FUNCTION,h=g.TYPE_STRING,e=g.TYPE_BOOLEAN,f=g.TYPE_OBJECT,c=g.TYPE_NUMBER,a=g.Definition;return{base_url:new a(h),FILENAME_FRAGMENT_BAD_CONTROL_CHARS:new a(h,{include:["vault","note"]}),FILENAME_FRAGMENT_BAD_SHELL_CHARS:new a(h,{include:["vault","note"]}),g_bigicons:new a(f,{include:"vault",sendIndirect:!1,write:!0}),g_icons:new a(f,{include:["vault","extensionDropdown"]}),g_applications:new a(f,{include:["vault","extensionDropdown",
"application"]}),g_emer_sharees:new a(f,{include:"vault"}),g_emer_sharers:new a(f,{include:"vault"}),g_enterpriseuser:new a(c,{sync:!0}),g_formfills:new a(f,{include:["vault","extensionDropdown","formFill","chooseProfile"]}),g_genpws:new a(f,{include:["vault","extensionDropdown"],write:!0}),g_identities:new a(f,{include:["vault","extensionDropdown"]}),g_identity:new a(h,{include:["vault","extensionDropdown"],sync:!0}),g_iscompanyadmin:new a(e,{sync:!0}),g_local_accts_version:new a(h,{include:"vault",
sync:!0}),g_local_key:new a(h),g_pendings:new a(f,{include:"vault"}),g_prefoverrides:new a(f,{include:["vault","extensionDropdown","preferences","login"]}),g_premium_exp:new a(f),g_prompts:new a(f),g_securenotes:new a(f,{include:["vault","extensionDropdown","note"]}),g_shares:new a(f),g_showcredmon:new a(e,{include:"vault",sync:!0}),g_sites:new a(f,{include:["vault","extensionDropdown","site","note"]}),g_pending_shares:new a(f,{include:["vault"]}),g_note_templates:new a(f,{include:["vault","note"]}),
g_username:new a(h),g_username_hash:new a(h,{include:"vault"}),g_reminders:new a(f,{include:["vault"],write:!0}),g_one_minute_signup_enabled:new a(e,{include:"vault"}),g_one_minute_signup_menu_enabled:new a(e,{include:"vault"}),lp_attaches:new a(f,{include:["vault","note"]}),lploggedin:new a(e,{sync:!0}),lpversion:new a(h,{include:"vault"}),rsaprivatekeyhex:new a(h,{include:"vault",write:!0}),siteCats:new a(f,{include:["vault","site"]}),addAttach:new a(b),addeditformfill:new a(b),addEmptyGroup:new a(b),
LPServer:{ajax:new a(b),xmlRequest:new a(b),textRequest:new a(b),jsonRequest:new a(b)},BackgroundServer:{emergencyAccess:{acceptOffer:new a(b),addRecipient:new a(b),declineOffer:new a(b),denyAccess:new a(b),getRecipientInfo:new a(b),getSharerInfo:new a(b),removeRecipient:new a(b),requestAccess:new a(b),unlinkAccount:new a(b),updateRecipient:new a(b)},identities:{add:new a(b),remove:new a(b),update:new a(b)},sharing:{individual:{shareItems:new a(b),unshareItem:new a(b),acceptShare:new a(b),rejectShare:new a(b),
inviteFriends:new a(b),getSentShareData:new a(b),getReceivedShareData:new a(b)},folder:{getFolders:new a(b),getPublicKeys:new a(b),create:new a(b),rename:new a(b),remove:new a(b),accept:new a(b),reject:new a(b),addMembers:new a(b),getMembers:new a(b),removeMember:new a(b),reinviteMember:new a(b),updateMemberPermissions:new a(b),getRestrictions:new a(b),updateRestrictions:new a(b),startDownloading:new a(b),stopDownloading:new a(b),restoreDeleted:new a(b),purgeDeleted:new a(b),convertToEnterprise:new a(b)}},
sitesAndNotes:{saveCustomNoteTemplate:new a(b),deleteCustomNoteTemplate:new a(b)}},changePassword:new a(b),deleteAid:new a(b),deleteformfill:new a(b),deleteGroup:new a(b),editAid:new a(b),fastEncryptAttachments:new a(b),generate_key:new a(b),get_securityChallengeScore:new a(b),gotourl:new a(b),launch:new a(b),launchApp:new a(b),loggedOut:new a(b),loglogin:new a(b),lpReportError:new a(b),make_lp_hash_iterations:new a(b),make_lp_key_hash:new a(b),make_lp_key_iterations:new a(b),moveIntoSharedFolder:new a(b),
moveSelectedToGroup:new a(b),openAllSites:new a(b),openAttach:new a(b),openexport:new a(b),openentconsole:new a(b),openfavorites:new a(b),openimport:new a(b),openseccheck:new a(b),openURL:new a(b),processCS:new a(b),refreshGroupNames:new a(b),refreshsites:new a(b),renameGroup:new a(b),saveFields:new a(b),saveSite:new a(b),singlefactor_reprompt:new a(b),switch_identity:new a(b),unlock_plug2web:new a(b),exportAttachment:new a(b),install_binary:new a(b),VaultToggle:{toggleVault3_0:new a(b)},increment_local_accts_version:new a(b),
AES:{bin2hex:new a(d,{exclude:"contentScript"}),Decrypt:new a(d,{exclude:"contentScript"}),Encrypt:new a(d,{exclude:"contentScript"}),hex2bin:new a(d,{exclude:"contentScript"}),hex2url:new a(d,{exclude:"contentScript"}),url2hex:new a(d,{exclude:"contentScript"})},can_copy_to_clipboard:new a(d,{exclude:"contentScript"}),canLaunchApplication:new a(d,{exclude:"contentScript"}),check_filename_badchars:new a(d,{exclude:"contentScript"}),crypto_btoa:new a(d,{exclude:"contentScript"}),db_prepend:new a(d,
{exclude:"contentScript"}),dec:new a(d,{exclude:"contentScript"}),enc:new a(d,{exclude:"contentScript"}),enccbc:new a(d,{exclude:"contentScript"}),encode_private_key:new a(d,{exclude:"contentScript"}),encode_public_key:new a(d,{exclude:"contentScript"}),fix_username:new a(d,{exclude:"contentScript"}),get_last_reprompt_time:new a(d,{exclude:"contentScript"}),get_mimetype_from_filename:new a(d,{exclude:"contentScript"}),get_personal_linked:new a(d,{exclude:"contentScript"}),get_random_password:new a(d,
{exclude:"contentScript"}),getbigicon:new a(d,{exclude:"contentScript"}),geticonurlfromrecord:new a(d,{exclude:"contentScript"}),gs:new a(d,{exclude:"contentScript"}),have_binary:new a(d,{exclude:"contentScript"}),isOffline:new a(d,{exclude:"contentScript"}),localStorage_getItem:new a(d,{exclude:"contentScript"}),localStorage_setItem:new a(d,{exclude:"contentScript"}),lp_gettld_url:new a(d,{exclude:"contentScript"}),lpCreatePass:new a(d,{exclude:"contentScript"}),lpdec:new a(d,{exclude:"contentScript"}),
lpenc:new a(d,{exclude:"contentScript"}),lpevent:new a(d,{exclude:"contentScript"}),lpmdec:new a(d,{exclude:"contentScript"}),lpmenc:new a(d,{exclude:"contentScript"}),parse_public_key:new a(d,{exclude:"contentScript"}),parse_private_key:new a(d,{exclude:"contentScript"}),parsemobile:new a(d,{exclude:"contentScript"}),punycode:{URLToASCII:new a(d,{exclude:"contentScript"})},RSAKey:new a(g.TYPE_CONSTRUCTOR,{exclude:"contentScript"}),set_last_reprompt_time:new a(d,{exclude:"contentScript"}),SHA256:new a(d,
{exclude:"contentScript"}),hostof:new a(d,{exclude:"contentScript"}),StringUtils:{translate:new a(d,{exclude:"contentScript"})},Preferences:{get:new a(d,{exclude:"contentScript"}),set:new a(d,{sendIndirect:!0,exclude:"contentScript"})},rsa_encrypt_privatekey:new a(d,{exclude:"contentScript"})}}(Interfaces);
(function(g){var b=Interfaces.TYPE_FUNCTION,d=Interfaces.TYPE_SYNC_FUNCTION,h=Interfaces.TYPE_STRING,e=Interfaces.TYPE_BOOLEAN,f=Interfaces.TYPE_OBJECT,c=Interfaces.Definition,b={countryfromip:new c(h,{include:"vault"}),g_loggedinoffline:new c(h,{include:"vault"}),g_loggedinonline:new c(h,{include:"vault"}),g_badgedata:new c(f,{include:["login","extensionDropdown","vault"]}),g_flags:new c(f,{include:"preferences"}),g_hideappearancebox:new c(e,{include:"preferences"}),g_hidehelptranslate:new c(e,{include:"preferences"}),
g_hidelogoffprefs:new c(e,{include:"preferences"}),g_hidenotes:new c(e,{include:"preferences"}),g_hiderecentlyusedlistsize:new c(e,{include:"preferences"}),g_hidesaedhotkey:new c(e,{include:"preferences"}),g_hidesearch:new c(e,{include:"preferences"}),g_hidevault:new c(e,{include:"preferences"}),g_hideshowvault:new c(e,{include:"preferences"}),g_is_linux:new c(e,{include:"preferences"}),g_is_win:new c(e,{include:["vault","preferences"]}),g_is_mac:new c(e,{include:"preferences"}),g_issafari:new c(e,
{include:"preferences"}),g_langs:new c(f,{include:"preferences"}),g_manual_login:new c(e,{include:"login",write:!0}),g_master_password_saved:new c(e,{include:"preferences"}),g_nopoll:new c(e,{include:"preferences"}),g_notification_data:new c(f,{include:["login","extensionDropdown","vault"]}),g_notification_type:new c(f,{include:["login","extensionDropdown"]}),g_offer_popupfill:new c(e,{include:"preferences"}),g_shownewloginoption:new c(e,{include:"preferences"}),lp_phpsessid:new c(h),lppassusernamehash:new c(e,
{include:"preferences"}),remembersignons:new c(e,{include:"login"}),g_userprefs:new c(f,{sync:!0}),g_gblprefs:new c(f,{sync:!0}),clearRecentTime:new c(e,{include:"extensionDropdown",sourceFunction:"getClearRecentTime"}),g_sites_tld:new c(e,{include:"extensionDropdown",sourceFunction:function(){return getmatchingsites(!1,!0,!1)}}),g_can_clear_clipboard:new c(e,{sourceFunction:"can_clear_clipboard"}),g_can_copy_to_clipboard:new c(e,{sourceFunction:"can_copy_to_clipboard"}),g_is_chrome_portable:new c(e),
g_user_debug_enabled:new c(e,{sourceFunction:"is_user_debug_enabled"}),g_have_nplastpass:new c(e,{sourceFunction:"have_nplastpass"}),g_have_native_messaging:new c(e,{sourceFunction:"have_native_messaging"}),g_have_ws:new c(e,{sourceFunction:"have_ws"}),create_account:new c(b),copytoclipboard:new c(b),clear_badge:new c(d,{sendIndirect:!0,exclude:"contentScript"}),clear_badge_text:new c(b),clearCache:new c(b),clearforms:new c(b),clearrecent:new c(b),createContextMenus:new c(b),DeleteOTP:new c(b),disableallalerts:new c(b),
disablepasswordmanager:new c(b),disablesitealert:new c(b),formfillexport:new c(b),get_saved_logins:new c(b),get_selected_tab:new c(b),get_selected_tab_data_no_extension:new c(b),loggedOut:new c(b),LP_do_login:new c(b),lpevent:new c(b),LPData:{getData:new c(b),setValue:new c(b)},LPPlatform:{openTabDialog:new c(b),isMac:new c(d,{exclude:"contentScript"}),isWin:new c(d,{exclude:"contentScript"})},openabout:new c(b),opendebugtab:new c(b),openentconsole:new c(b),openexport:new c(b),openfavorites:new c(b),
openhelp:new c(b),openimport:new c(b),openimportchrome:new c(b),openlastpassexport:new c(b),openmyaccount:new c(b),openprefs:new c(b),openprint:new c(b),openseccheck:new c(b),opensessions:new c(b),openURL:new c(b),openvault:new c(b),saveall:new c(b),start_trial:new c(b),unprotect_data:new c(b),wlanexport:new c(b),lpWriteAllPrefs:new c(b),saveSiteFromSubmit:new c(b),get_selected_tab_data:new c(b),fillGeneratedPassword:new c(b),saveAllSite:new c(b),repromptSuccess:new c(b),open_login:new c(b),fillaid:new c(b),
fillform:new c(b),setup_hotkeys:new c(b),IntroTutorial:{getState:new c(b),setState:new c(b)},sendLpImprove:new c(b),can_clear_clipboard:new c(d,{exclude:"contentScript"}),fix_username:new c(d,{exclude:"contentScript"}),get_lplanguage:new c(d,{exclude:"contentScript"}),getClearRecentTime:new c(d,{include:"extensionDropdown"}),getmatchingsites:new c(d,{exclude:"contentScript"}),gettaburl:new c(d,{exclude:"contentScript"}),gs:new c(d,{exclude:"contentScript"}),have_binary:new c(d,{exclude:"contentScript"}),
include_language:new c(d,{exclude:"contentScript"}),is_chrome_portable:new c(d,{exclude:"contentScript"}),is_opera_chromium:new c(d,{exclude:"contentScript"}),is_user_debug_enabled:new c(d,{exclude:"contentScript"}),setcurrenttabid:new c(d,{exclude:"contentScript"}),setcurrenturl:new c(d,{exclude:"contentScript"})};Interfaces.extend(g,b)})(Interfaces.BackgroundInterface);
