BackgroundServer=function(m){LPServer.initialize(m,{ajax:function(a){a.data&&(a.data.method=get_method());LPPlatform.ajax(a)}});var c=function(a){return function(){a.apply(this,arguments);increment_local_accts_version();rewritelocalfile()}},h=function(a,d,b){d instanceof Array?d.push(a):d[a[b]]=a},l=c(h),f=function(a,d,b){if(d instanceof Array)for(var e=0,c=d.length;e<c;++e){if(a[b]===d[e][b]){d[e]=a;break}}else d[a[b]]=a},k=c(f),g=function(a,d,b){if(a instanceof Array)for(var e=0,c=a.length;e<c;++e){if(b===
a[e][d]){a.splice(e,1);break}}else delete a[d]},j=c(g);return{emergencyAccess:{updateRecipient:function(a){var d=a.success;a.success=function(){k(a.params.recipient,g_emer_sharees,"username");d(a.params.recipient)};LPServer.emergencyAccess.updateRecipient(a)},addRecipient:function(a){var d=a.success;a.success=function(){l(a.params.recipient,g_emer_sharees,"username");d(a.params.recipient)};LPServer.emergencyAccess.addRecipient(a)},removeRecipient:function(a){a.success=LPServer.extendCallback(a.success,
function(){j(g_emer_sharees,"username",a.params.id)});LPServer.emergencyAccess.removeRecipient(a)},getRecipientInfo:function(a){LPServer.emergencyAccess.getRecipientInfo(a)},getSharerInfo:function(a){LPServer.emergencyAccess.getSharerInfo(a)},acceptOffer:function(a){var d=a.success;a.success=function(){var b=a.params.sharer;b.accepted="1";k(b,g_emer_sharers,"username");d(b)};LPServer.emergencyAccess.acceptOffer(a)},declineOffer:function(a){a.success=LPServer.extendCallback(a.success,function(){j(g_emer_sharers,
"username",a.params.email)});LPServer.emergencyAccess.declineOffer(a)},requestAccess:function(a){a.callbacks=a.callbacks||{};var d=a.callbacks.successLinked;a.callbacks.successLinked=function(a,b){var c=b.params.sharer;c.confirmed="1";c.allowed_access="1";c.linked="1";c.override_date=new Date;refreshsites();d(c,b)};var b=a.callbacks.successGranted;a.callbacks.successGranted=function(a,d){var c=d.params.sharer;c.confirmed="1";c.override_date=new Date;c.override_date.setTime(c.override_date.getTime()+
36E5*c.hours_to_override);b(c,d)};LPServer.emergencyAccess.requestAccess(a)},denyAccess:function(a){a.success=LPServer.extendCallback(a.success,function(){var d;a:if(g_emer_sharees instanceof Array){d=0;for(var b=g_emer_sharees.length;d<b;++d)if(a.params.email===g_emer_sharees[d].username){d=g_emer_sharees[d];break a}d=void 0}else d=g_emer_sharees.username;d.confirmed="0";d.allowed_access="0"});LPServer.emergencyAccess.denyAccess(a)},unlinkAccount:function(a){a.success=LPServer.extendCallback(a.success,
c(function(){if(a.params.folderID)delete g_sites[a.params.folderID];else for(var d in g_sites){var b=g_sites[d];if("http://group"===b.url&&b.group===a.params.email){delete g_sites[d];break}}}));LPServer.emergencyAccess.unlinkAccount(a)}},identities:{add:function(a){var d=a.success;a.success=function(b){var c=a.params.identity;c.iid=LPServer.getAttr(b,"iid","");l(c,g_identities,"iid");d(c)};LPServer.identities.add(a)},remove:function(a){a.success=LPServer.extendCallback(a.success,function(){j(g_identities,
"iid",a.params.id)});LPServer.identities.remove(a)},update:function(a){var d=a.success;a.success=function(){var b=a.params.identity;k(b,g_identities,"iid");d(b)};LPServer.identities.update(a)}},sharing:{individual:{shareItems:function(a){LPServer.sharing.individual.shareItems(a)},unshareItem:function(a){LPServer.sharing.individual.unshareItem(a)},acceptShare:function(a){a.success=LPServer.extendCallback(a.success,function(){refreshsites()});LPServer.sharing.individual.acceptShare(a)},rejectShare:function(a){a.success=
LPServer.extendCallback(a.success,function(){j(g_pendings,"id",a.params.id)});LPServer.sharing.individual.rejectShare(a)},inviteFriends:function(a){LPServer.sharing.individual.inviteFriends(a)},getSentShareData:function(a){LPServer.sharing.individual.getSentShareData(a)},getReceivedShareData:function(a){LPServer.sharing.individual.getReceivedShareData(a)}},folder:{getFolders:function(a){LPServer.sharing.folder.getFolders(a)},getPublicKeys:function(a){LPServer.sharing.folder.getPublicKeys(a)},create:function(a){a.success=
LPServer.extendCallback(a.success,c(function(a,b){b.shareInfo.sharekeyaes=lpmenc(AES.bin2hex(b.shareInfo.key),!0,g_local_key);h(b.shareInfo,g_shares,"id");h(b.sharedFolder,g_sites,"aid")}));a.params.username=g_username;LPServer.sharing.folder.create(a)},rename:function(a){a.success=LPServer.extendCallback(a.success,c(function(a,b){f(b.shareInfo,g_shares,"id");f(b.sharedFolder,g_sites,"aid")}));LPServer.sharing.folder.rename(a)},remove:function(a){a.success=LPServer.extendCallback(a.success,c(function(a,
b){f(b.shareInfo,g_shares,"id");for(var c in g_sites)g_sites[c].sharefolderid===b.shareInfo.id&&delete g_sites[c]}));LPServer.sharing.folder.remove(a)},accept:function(a){a.success=LPServer.extendCallback(a.success,function(){g(g_pending_shares,"id",a.params.shareInfo.id);refreshsites()});LPServer.sharing.folder.accept(a)},reject:function(a){a.success=LPServer.extendCallback(a.success,c(function(){g(g_pending_shares,"id",a.params.shareInfo.id)}));LPServer.sharing.folder.reject(a)},addMembers:function(a){LPServer.sharing.folder.addMembers(a)},
getMembers:function(a){LPServer.sharing.folder.getMembers(a)},removeMember:function(a){LPServer.sharing.folder.removeMember(a)},reinviteMember:function(a){LPServer.sharing.folder.reinviteMember(a)},updateMemberPermissions:function(a){LPServer.sharing.folder.updateMemberPermissions(a)},getRestrictions:function(a){LPServer.sharing.folder.getRestrictions(a)},updateRestrictions:function(a){LPServer.sharing.folder.updateRestrictions(a)},startDownloading:function(a){a.success=LPServer.extendCallback(a.success,
function(){refreshsites()});LPServer.sharing.folder.startDownloading(a)},stopDownloading:function(a){a.success=LPServer.extendCallback(a.success,c(function(a,b){f(b.shareInfo,g_shares,"id");for(var c in g_sites)g_sites[c].sharefolderid===b.shareInfo.id&&delete g_sites[c]}));LPServer.sharing.folder.stopDownloading(a)},restoreDeleted:function(a){a.success=LPServer.extendCallback(a.success,c(function(a,b){f(b.shareInfo,g_shares,"id");refreshsites()}));LPServer.sharing.folder.restoreDeleted(a)},purgeDeleted:function(a){a.success=
LPServer.extendCallback(a.success,c(function(){g(g_shares,"id",a.params.shareid);g(g_sites,"aid",a.params.shareid)}));LPServer.sharing.folder.purgeDeleted(a)},convertToEnterprise:function(a){a.success=LPServer.extendCallback(a.success,c(function(a,b){f(b.shareInfo,g_shares,"id");f(b.sharedFolder,g_sites,"aid")}));LPServer.sharing.folder.convertToEnterprise(a)}}},sitesAndNotes:{saveCustomNoteTemplate:function(a){a.success=LPServer.extendCallback(a.success,c(function(a,b){h(b,g_note_templates,"id")}));
LPServer.sitesAndNotes.saveCustomNoteTemplate(a)},deleteCustomNoteTemplate:function(a){a.success=LPServer.extendCallback(a.success,c(function(){g(g_note_templates,"id",a.params.id)}));LPServer.sitesAndNotes.deleteCustomNoteTemplate(a)}}}}(this);
