LPPlatform={};
(function(){LPPlatform.openURL=function(a){bg.openURL(a)};LPPlatform.getBaseURL=function(){return bg.get("base_url")};LPPlatform.doAjax=function(a){$.ajax(a)};LPPlatform.ajax=function(a){bg.isOffline()?a.error&&a.error(null,null,"offline"):LPPlatform.doAjax(a)};LPPlatform.getOpenGroups=function(){var a=bg.localStorage_getItem(bg.db_prepend(bg.get("g_username_hash")+".savedtree"));if(null!==a){for(var c={},a=LPProxy.decrypt(a).split(","),e=0,g=a.length;e<g;++e){var f=a[e];0===f.indexOf("_")&&(f=f.substring(1));
c[f]=!0}return c}return null};LPPlatform.setOpenGroups=function(a){for(var c=0,e=a.length;c<e;++c)a[c]="_"+a[c];a=LPProxy.encrypt(a.join(","));bg.localStorage_setItem(bg.db_prepend(bg.get("g_username_hash")+".savedtree"),a)};LPPlatform.initialized=function(){return!0};LPPlatform.getHTML=function(a,c){$.ajax({url:a,success:c,dataType:"text"})};LPPlatform.loadedPreferences=function(){return LPTools.hasProperties(bg.get("g_userprefs"))};LPPlatform.openAttachment=function(a){bg.openAttach(a._parentNote.getID(),
a.getID())};LPPlatform.saveAttachment=function(a){bg.exportAttachment(a._parentNote.getID(),a.getID())};LPPlatform.logException=function(a){var c="string"===typeof a?a:a.message;a.stack&&(c+="\n"+a.stack);LPPlatform.logError(c)};LPPlatform.logError=function(a){a="Page: "+window.location.href+" Error: "+a;try{console.error(a),bg.lpReportError("VAULT_4_0: "+a)}catch(c){}};LPPlatform.addEventListener=function(a){for(var c=[],e=1;e<arguments.length;++e)c.push(arguments[e]);a.addEventListener.apply(a,
c)};LPPlatform.removeEventListener=function(a){for(var c=[],e=1;e<arguments.length;++e)c.push(arguments[e]);a.removeEventListener.apply(a,c)};LPPlatform.handleAcctsIFrameLoaded=function(){};LPPlatform.canBackgroundOpenPopover=function(){return!0};LPPlatform.generateSharingKeys=function(a){bg.generateSharingKeys(a)};LPPlatform.getResourcePath=function(a){return a};LPPlatform.canPreventBlur=function(){return!0};LPPlatform.getBackgroundData=function(a){return a};LPPlatform.showIntroTutorial=function(){return!1};
LPPlatform.supportsBinary=function(){return!0};LPPlatform.openKeyboard=function(){bg.LPPlatform.openTabDialog("login",{virtualKeyboard:!0})};LPPlatform.getImportHandler=function(){return"importerHandler"};LPPlatform.showDownloader=function(){return!1}})();
(function(a){var c=$(document.body),e=$(document.getElementsByTagName("html")),g,f=function(a,b){c.css({height:a,width:b});e.css({height:a,width:b})};g=function(a,b){bg.LPPlatform.isMac()?(f(a+1,b),setTimeout(function(){f(a,b)},50)):f(a,b)};a.setLoginPopoverSize=function(a,b){g(a,b)};a.setDropdownPopoverSize=function(a,b){g(a,b)};a.closePopup=function(d){(d||0===Dialog.prototype.getDialogCount()&&0===LPDialog.getPendingCount())&&a.doClosePopup()};a.doClosePopup=function(){window.close()};a.closeTab=
function(){window.close()};a.getLoginDialog=function(){return dialogs.login};a.openLoginPopover=function(){!bg.get("lploggedin")&&bg.get("g_badgedata")&&"notification"===bg.get("g_badgedata").cmd?(dialogs.notification.open({notification:bg.get("g_notification_data"),onResize:function(d,b){a.setLoginPopoverSize(d,b)}}),bg.clear_badge()):a.getLoginDialog().open({isPopup:!0,onResize:function(d,b){a.setLoginPopoverSize(d,b)},onClose:function(){a.closePopup()}})};a.requiresData=function(a){switch(a){case "chooseProfile":return!0}return!1};
a.openDropdownPopoverDialog=function(d,b){$("#container").LP_hide();LPTools.removeKeyBoardNavigation();a.requiresData(d)&&LPProxy.initializeModel();b=$.extend(b,{onResize:function(d,b){a.setDropdownPopoverSize(d,b)},onClose:function(){a.closePopup()}});dialogs[d].open(b)};a.openDropdownPopover=function(){var d=bg.get("g_badgedata");if(d&&"notification"===d.cmd){switch(d.alerttype){case "duplicate":a.openDropdownPopoverDialog("duplicatePassword",{notification:d});break;case "weak":a.openDropdownPopoverDialog("weakPassword",
{notification:d})}switch(d.type){case "error":a.openDropdownPopoverDialog("notification",{notification:bg.get("g_notification_data")})}bg.clear_badge()}else $("#container").LP_show(),ExtensionDropdown.setup()};a.checkBrowserPasswordManager=function(){};a.setupDropdownImportMenu=function(a){a.addClass("singleImportOption");a=$("#importMenuItemMain");a.unbind("click");a.bind("click",function(){bg.lpevent("m_i");bg.openimport()})};a.getUnavailablePreferences=function(){return{clearClipboardSecsVal:!bg.can_clear_clipboard(),
openpopoverHk:!a.canBackgroundOpenPopover(),pollServerVal:bg.get("g_nopoll"),storeLostOTP:"0"===bg.get("g_prefoverrides").account_recovery,showvault:bg.get("g_hidevault")||bg.get("g_hideshowvault"),homeHk:bg.get("g_hidevault")||bg.get("g_hideshowvault"),saveallHk:bg.get("g_hidesaedhotkey"),searchHk:bg.get("g_hidesearch"),usepopupfill:!bg.get("g_offer_popupfill"),recentUsedCount:bg.get("g_hiderecentlyusedlistsize"),searchNotes:bg.get("g_hidenotes"),idleLogoffVal:!(bg.get("g_is_win")||bg.get("g_is_mac")||
bg.get("g_is_linux")),enablenamedpipes:bg.get("lppassusernamehash")||!(bg.get("g_is_win")||bg.get("g_is_mac")||bg.get("g_is_linux"))||bg.is_chrome_portable(),enablenewlogin:!0}};a.getPreferencesRequiringBinary=function(){return{enablenamedpipes:!0}};a.handlePreferenceChanges=function(a){!1===a.storeLostOTP&&bg.DeleteOTP()};a.resizeTo=function(a,b){window.resizeTo(a,b)};a.openCreateAccount=function(){bg.LPPlatform.openTabDialog("createAccount")};a.showIntroTutorial=function(){var a=LPProxy.getModelCount();
if("US"!==bg.get("countryfromip"))return 0===a&&LPVault.openTour(),!1;var b=LPProxy.getPreference("ShowIntroTutorial",!0);b&&0===a?dialogs.introTutorialWelcome.open():b&&1===a?bg.IntroTutorial.getState(function(a){a.enabled&&(Topics.get(Topics.EXPAND_ALL).publish(),dialogs.introTutorialComplete.open({tutorialState:a}))}):LPVault.openTour()}})(LPPlatform);
